### ISSUE TITLE
Implement non-anchoring slider

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#1]
As an experiment designer, I want to be able to include a slider in SurveyJS surveys so that we can ask questions like "feeling thermometers". One hazard with sliders is that the slider handle serves as an "anchor" for the response that participants will make, and so may bias the outcomes of the survey.

In empirica (V1 at least) there is a [slider](https://github.com/empiricaly/meteor-empirica-slider) with no handle until the participant clicks on the bar. This is a styling wrapper around blueprint's slider. SurveyJS has two slider plugins ([Nouislider](https://surveyjs.io/form-library/examples/custom-widget-nouislider/reactjs) and [bootstrap slider](https://surveyjs.io/form-library/examples/custom-widget-bootstrapslider/reactjs)) which we may be able to modify with similar styling changes to use in our surveys.

**Comment by willschulz** [comment]
Could we just set the slider to start out at the center position by default?  This is how I've implemented sliders in Qualtrics surveys before, and though I agree handle-less might be even better, center-default should be fine.

**Comment by JamesPHoughton** [comment]
There is a [slider](https://www.w3schools.com/howto/howto_js_rangeslider.asp) input built into HTML5, that is [well supported by modern browsers](https://caniuse.com/input-range). 

There are some [nice](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist#range_type) [examples](https://stackoverflow.com/a/61205099/6361632) of using a `datalist` to add scale labels to a slider. 

This should be easy. Unfortunately, SurveyJS doesn't use what seems like a fairly straightforward solution.

SurveyJS does allow some sliders as third party plugins:
 - [noUISlider](https://surveyjs.io/form-library/examples/custom-widget-nouislider/reactjs) implemented here: https://github.com/surveyjs/custom-widgets/blob/master/src/nouislider.js, based on https://refreshless.com/nouislider/
 - [bootstrap slider](https://surveyjs.io/form-library/examples/custom-widget-bootstrapslider/reactjs) 

But they are old, probably because they have been replaced by the built-in `<input type="range/>` in most applications. They also depend on some heavyweight libraries (bootstrap or Jquery) which we would otherwise not need to include in our libraries. It would be lovely not to have to add lots of dead weight (load time, complexity, etc) to our code.

We could add a [custom widget](https://surveyjs.io/survey-creator/documentation/customize-question-types/create-custom-widgets#totally-replace-the-existing-question-input-by-custom-widget) to our surveys library that we could import in the `surveyFactory`, using the input-range component. This would also let us specify the custom CSS needed to hide the handle.

**Comment by JamesPHoughton** [comment]
This library documentation is really bad. Turns out you can do a range slider by using a single input question with type "range" (not in docs) but you can't actually set what the endpoints are. So, close to useless?

https://github.com/surveyjs/survey-library/issues/444#issuecomment-324552992

It does mean we should be able to just modify the range component rather than having to create one from scratch, however...

**Comment by JamesPHoughton** [comment]
Added the range slider and some custom styling/handling. What we need now is just some CSS wizardry to make it look good:
![Screen Shot 2023-01-30 at 10 57 01 AM](https://user-images.githubusercontent.com/4304478/215532228-bac85b5c-12e1-4d74-9f15-74d976dbd568.png)

**Comment by JamesPHoughton** [comment]
Also, for some reason the dataList isn't using the right values, so that two questions on the same page with different tickmarks are showing up using the last element's tickmarks. (Even though the min/max/step are working properly).

```json
"elements": [
        {
          "type": "text",
          "inputType": "range",
          "name": "republicanImportance",
          "title": "How important is being a Republican to you?",
          "description": "Below is a range from 0 to 100 indicating how important this is to you. Click on any space within this range and a bar will appear. Feel free to move that bar around to the number that best represents your answer.",
          "min": 0,
          "max": 100,
          "step": 1,
          "valueLabels": [
            { "value": 0, "text": "Not important at all" },
            { "value": 25, "text": "" },
            { "value": 50, "text": "Moderately Important" },
            { "value": 75, "text": "" },
            { "value": 100, "text": "Extremely Important" }
          ]
        },
        {
          "type": "text",
          "inputType": "range",
          "name": "sleepHours",
          "title": "How many hours did you sleep last night?",
          "min": 0,
          "max": 12,
          "step": 1,
          "progressBar": true,
          "valueLabels": [
            { "value": 0, "text": "0" },
            { "value": 10, "text": "10" },
            { "value": 12, "text": "12" }
          ]
        }
      ]
```
Shows:
![image](https://user-images.githubusercontent.com/4304478/215543484-60737234-8976-4638-8ffd-a65085442e29.png)

**Comment by JamesPHoughton** [comment]
- Green underbar is actually a horizontal scroll bar, because the range slider is too wide for its container, and sticks its ears out the end. Setting the width to 99% of the container means that there isn't an overflow.

- Turns out we actually want to enable the thumb on mouseDown, not when a value has been entered (which seems to happen on mouseUp?) Also, the `afterRender` method only gets called once, so we can't count on it to add the class label without a callback anyways. The solution is to add an event listener to the slider:
```js
slider.addEventListener("mousedown", () => slider.classList.add("sliderClicked"));
```

**Comment by JamesPHoughton** [comment]
- The issue with having the scale only use the last set of values attached to it was a *capitalization* mistake. 🤦‍♂️ the type attribute for new parameters doesn't use camelCase, as I had assumed, so should have been:
```js
    name: "valueLabels",
    type: "itemvalues",
```

**Comment by JamesPHoughton** [comment]
Some examples of styling ticks:
- https://codepen.io/vsync/pen/mdEJMLv
- https://stackoverflow.com/a/64306268/6361632

**Comment by JamesPHoughton** [comment]
Current status:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/4304478/217865678-63df7e67-63e0-4e64-b8cd-7fbe88918841.png">
- thumb appears on mousedown
- different scales show up
- progress bar is gone

Still to do:
- Add ticks at proper locations on the bar
- center labels on the ticks, wrap text if necessary

**Comment by JamesPHoughton** [comment]
Closed by https://github.com/Watts-Lab/surveys/pull/112
