### ISSUE TITLE
Question order randomization

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#108]
There are times when we want question orders to be randomized, (ie, sometimes ask about republicans first, sometimes about democrats). SurveyJS is supposed to be able to do this randomization, but I am not sure that it is doing this correctly. We need to:

## a) check that it actually happens 
I'm not sure how to check for randomization in cypress, as it expects things to be deterministic. We could:
- compare against the order that questions would come in if they were not randomized, and make sure they aren't in that order
- build up a test to run the same survey twice, and check that the question ordering differs between runs (assuming that surveyJS doesn't try and randomize across participants but keep each participant the same.

## b) record the order as seen by participants in the `result` object
The order that the participants actually see the question is scientifically interesting

A good place to start would be one of the listening behaviors surveys, as it has 10 questions that should be shown in a randomized order.

**Comment by JamesPHoughton** [comment]
We have completed `a)`, but not `b)`

**Comment by JamesPHoughton** [comment]
May use the api built into surveyjs, documentation is here: https://surveyjs.io/form-library/documentation/api-reference/survey-data-model.

We use this library in the `labeledRange` custom component.

**Comment by gumillie222** [comment]
#137 questions are randomized, tests updated, and randomized order are returned as part of scoreFunc

look into partisanFeelingThermo: questions are on different pages, so having trouble randomizing the order
