### ISSUE TITLE
Remove "thanks for completing" as completion text

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#127]
Sometimes if it takes a while to submit the survey in empirica, it shows a "thanks for completing the survey" which is standard for surveyJS. We should change this text so it says something like "loading..."

https://surveyjs.answerdesk.io/ticket/details/t3029/how-to-change-the-complete-survey-message-thank-you-for-completing-the-survey

Surveys can be prototyped in a visual editor here: https://surveyjs.io/create-free-survey but we should check the json that it gives us for conciseness and correctness.

**Comment by JamesPHoughton** [comment]
What we'll probably need to do is modify the survey.json files to include the `showCompletedPage": false,`

```json

{
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "title": "test question",
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ]
    }
   ]
  }
 ],
 "showCompletedPage": false <<-- add to surveys
}
```

We should add a cypress test to check that there is no after-message displayed.

**Comment by JamesPHoughton** [comment]
One last thing for this issue @gumillie222 - would you mind updating the project readme and the new survey issue template (here: https://github.com/Watts-Lab/surveys/blob/main/.github/ISSUE_TEMPLATE/new-survey.md) to give some instructions about making sure that this flag is set, so that future surveys behave the same way? =)

**Comment by gumillie222** [comment]
sure!

**Comment by JamesPHoughton** [comment]
Closed by https://github.com/Watts-Lab/surveys/pull/135
