### ISSUE TITLE
Implement the Cognitive Reflection Test (CRT) from Surveyor

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/surveys#15]
Implement the CRT survey ([found here](https://github.com/Watts-Lab/surveyor/blob/main/surveys/CRT.csv)) in SurveyJS, including a result named `CRT` which is an aggregation of the responses, scaled to a 0–1 interval. Other variables can have names like `CRT_eggs`.

**Comment by JamesPHoughton** [comment]
Done
