### ISSUE TITLE
Create an issue template for new survey additions

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#18]
We have a few issues which all follow a similar format, as they are all for adding particular surveys from the literature to this repo. (e.g. https://github.com/Watts-Lab/surveys/issues/15, https://github.com/Watts-Lab/surveys/issues/14, https://github.com/Watts-Lab/surveys/issues/12, https://github.com/Watts-Lab/surveys/issues/11) 

As a maintainer of this repo I want to ensure that all of the surveys in this repo have a consistent format, so that we can access them programmatically and communicate them clearly.

As a potential outside contributor to this repo, I want to know what will be expected of me in adding a survey to this repository.

- [ ] create an issue template that has a checklist for how to include a new survey, describing the format of the survey and what you need to do to include a new survey

**Comment by JamesPHoughton** [comment]
Useful documentation on creating issue templates is here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by isaacgat** [comment]
https://docs.google.com/document/d/1sa6OChfkzDemu0_CU_QFSvm26GqqOsezmfxZ7TRh4qU/edit?usp=sharing

^ Checklist for survey

**Comment by JamesPHoughton** [comment]
Committed here: https://github.com/Watts-Lab/surveys/blob/main/.github/ISSUE_TEMPLATE/new-survey.md
