### ISSUE TITLE
Edits to RME questions

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#189]
@markwhiting what do you think about these possible improvements to rmeTen:
- [ ] make questions mandatory
- [ ] hide the "previous" button so participants can't go back to a prior question
![image](https://github.com/user-attachments/assets/1f351e74-73be-4d93-8839-bd7046601654)

**Comment by markwhiting** [comment]
Both fine with me!

@amirrr — do you recall if we had strong reasons for either of these? I think I actually thought it was required, and that we didn't have a back button (because we had removed it in Surveyor)

**Comment by amirrr** [comment]
> Both fine with me!
> 
> @amirrr — do you recall if we had strong reasons for either of these? I think I actually thought it was required, and that we didn't have a back button (because we had removed it in Surveyor)

No they were there as default and I didn't remove the back button. We can remove them and also make them required.

**Comment by JamesPHoughton** [comment]
completed in https://github.com/Watts-Lab/surveys/pull/190
