### ISSUE TITLE
Create short format Team Viability survey

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#30]
A lot of the description for shortening and validating this survey is in: https://github.com/Watts-Lab/surveys/issues/12.
I think  4 +/- 2 questions should get us a lot of value without being tedious. For the summer, lets pick some based on our own judgement, that will support our testing. In the fall we can identify and evaluate a subset that we will use for longer-term testing.

**Comment by isaacgat** [comment]
We narrowed down the 20 questions listed in the paper to 6 unique questions that touch on the viability measures we care most about while reducing redundancy between overlapping or irrelevant questions.

**2. This team is capable of working together as a unit.** 
- Tells us if the participant felt like the group was cohesive in working together
**3. This team would work well together in the future.** 
- Tells us if the participant believes the group could function together if reconvened later on.
**4. As a team, this work group shows signs of falling apart.** 
a.) Tells us if the participant believes the group may have or will be unable to work together
b.) Serves as a negative Likert scale question to fight answer fatigue and possibly test for inconsistencies between respondents that answer these questions disingenuously
**5. Most of the members of this team would welcome the opportunity to work as a group again in the future.**
- Asks participant to make a judgment call about the feelings of others in the group--may serve as a unique data point
**19. This team has what it takes to persist in the face of obstacles.**
- Tells us if participant believes in the group's resilience
**20. This team will still be successful even if the members do not like one another.** 
- This question touches on the heart of our experiment, which is to test if the members of the group are able to deliberate effectively even in the face of identity disparities and conflicts

**Comment by markwhiting** [comment]
Cool. Let me know if you want to look at some example data for this (i.e., data from the 14 question version that I collected over hundreds of teams) to see if there's any statistical motivation for a particular selection of questions.

**Comment by isaacgat** [comment]
https://github.com/Watts-Lab/deliberation-empirica/pull/109#issue-1269662606

^ Updated survey PR
