### ISSUE TITLE
Participant topic survey

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#32]
As a scientist, I want to understand how the participants' discussion about a topic is influenced by their personal experience with and knowledge of the topic itself, so that I can better predict outcomes for particular groups. Some of the player/topic interactions I'm interested in include:

- How familiar are you with the topic?
- How much would you be influenced by the policy being discussed?

It would be useful to look to the literature and see if other researchers have already designed and used questions similar to these to get at participants' experiences. Ideally we could implement pre-validated questions and would not need to do the work of justifying our own question writing.

**Comment by kepstein23** [comment]
- How personally tied are you to this issue
- How familiar are you with the issue
- How happy/upset would you be if the government/society adopted your stance/the opposite stance on this topic?

**Comment by kepstein23** [comment]
- How personally tied are you to this issue
- How familiar are you with the issue
- How happy/upset would you be if the government/society adopted your stance/the opposite stance on this topic?

**Comment by kepstein23** [comment]
How much influence do you have on the outcome

**Comment by JamesPHoughton** [comment]
Ideally, these questions would be applicable to a variety of types of questions:

#### General "societal level" questions:
1. Should abortion be legal?
2. Can Alternative Energy Effectively Replace Fossil Fuels?
3. Should Washington, DC, and Puerto Rico Be Granted US Statehood?


#### Group-specific questions:
1. Should Dress Codes Be Implemented and Enforced?
2. 

#### Individual level questions:
1. Should humans consume dairy milk?
2. 


Here are som suggestions from GPT:

How familiar are you with the topic?
a) Very familiar
b) Moderately familiar
c) Slightly familiar
d) Not familiar at all

How often do you engage in discussions or activities related to the topic?
a) Very frequently
b) Occasionally
c) Rarely
d) Never

Have you conducted any research or sought information about the topic?
a) Extensively
b) Somewhat
c) Very little
d) None at all

Do you personally know anyone directly affected by the topic?
a) Yes, many people
b) Yes, a few people
c) Maybe one person
d) No, I don't know anyone affected

How much power or influence do you believe you have to shape the outcome or decisions related to the topic?
a) A great deal
b) Some influence
c) Very little influence
d) No influence at all

How emotionally invested are you in the topic?
a) Extremely invested
b) Somewhat invested
c) Neutral
d) Not invested at all

Have you actively participated in any related events or protests?
a) Yes, multiple times
b) Yes, once or twice
c) No, but I support those who do
d) No, I haven't participated in any events

How much do the outcomes or decisions related to the topic directly impact your life?
a) Significantly
b) Moderately
c) Minimally
d) Not at all

Have you had personal experiences that influenced your opinion on the topic?
a) Yes, multiple experiences
b) Yes, a few experiences
c) Maybe one experience
d) No personal experiences

How much do you value the opinions of experts and authorities on the topic?
a) Highly value them
b) Consider them to some extent
c) Don't consider them much
d) Completely disregard them

Have you engaged in conversations or debates about the topic in the past?
a) Frequently
b) Occasionally
c) Rarely
d) Never

How open are you to changing your opinion about the topic based on new information or perspectives?
a) Very open
b) Somewhat open
c) Reluctant to change
d) Not open at all

How much media coverage or information exposure have you had regarding the topic?
a) Extensive coverage
b) Some coverage
c) Minimal coverage
d) No coverage at all

Are you actively involved in any organizations or communities related to the topic?
a) Yes, actively involved
b) Connected but not actively involved
c) No, but interested in joining
d) Not involved at all

How much do you believe your personal values and beliefs influence your stance on the topic?
a) They strongly influence my stance
b) They somewhat influence my stance
c) They have minimal influence on my stance
d) They don't influence my stance at all


Which of the following best describes your level of technical expertise or knowledge about the topic?
a) Expert/professional in the field
b) Advanced knowledge and understanding
c) Basic understanding
d) Limited knowledge or unfamiliar with technical aspects

Have you received formal education or training specifically related to the topic?
a) Yes, extensively
b) Yes, to some extent
c) No, but I have informal knowledge/experience
d) No, I have no formal or informal knowledge/experience

How confident are you in explaining the technical details and concepts associated with the topic?
a) Very confident
b) Somewhat confident
c) Not very confident
d) Not confident at all

Have you worked professionally or conducted research related to the topic?
a) Yes, extensively
b) Yes, to some extent
c) No, but I have personal experience
d) No, I have no professional or personal experience

Have you published or contributed to any works (e.g., papers, articles, projects) related to the topic?
a) Yes, multiple publications/contributions
b) Yes, one or a few publications/contributions
c) No, but I have some unpublished work
d) No, I haven't published or contributed anything related

How familiar are you with the specialized terminology and jargon commonly used in discussions about the topic?
a) Very familiar, I can confidently use and understand the terminology
b) Moderately familiar, I understand most terms but may struggle with some
c) Slightly familiar, I recognize a few terms but lack in-depth understanding
d) Not familiar at all, the terminology is largely unfamiliar to me

Have you participated in any professional conferences or events related to the topic?
a) Yes, regularly
b) Yes, occasionally
c) No, but I have attended some events as an observer
d) No, I haven't attended any professional conferences or events

How up-to-date are you with the latest advancements, research, or trends in the field/topic?
a) Very up-to-date, actively follow and engage with new developments
b) Fairly up-to-date, stay informed through various sources
c) Somewhat up-to-date, but not actively seeking new information
d) Not up-to-date, rely on older or limited information

Do you possess any specialized certifications or credentials relevant to the topic?
a) Yes, multiple certifications/credentials
b) Yes, one or a few certifications/credentials
c) No, but I have relevant informal training or experience
d) No, I don't possess any certifications or credentials

How comfortable are you engaging in technical discussions or debates about the topic with experts in the field?
a) Very comfortable, I can hold my own and contribute effectively
b) Somewhat comfortable, but may struggle with complex technical aspects
c) Not very comfortable, prefer discussions at a more basic level
d) Not comfortable at all, feel overwhelmed by technical discussions


Do you feel adequately informed about the various options and alternatives related to the topic?
a) Yes, I have a thorough understanding of the options and alternatives available
b) Somewhat, I have some knowledge but would like more information
c) Not entirely, I feel there may be additional options or alternatives I'm not aware of
d) No, I lack sufficient information about the options and alternatives

Have you conducted sufficient research or sought out relevant information about the topic?
a) Yes, extensively
b) Yes, to some extent
c) No, but I have gathered basic information
d) No, I haven't conducted any research or sought out information

Do you believe you have a comprehensive understanding of the potential consequences or impacts associated with each decision option?
a) Yes, I have considered and understand the potential consequences thoroughly
b) Partially, I have some understanding but may need more information
c) Not fully, I feel there may be additional consequences or impacts I haven't considered
d) No, I lack sufficient information about the potential consequences or impacts

How confident do you feel in your ability to evaluate the credibility and reliability of the information you have gathered?
a) Very confident, I have experience and skills in evaluating information sources
b) Moderately confident, but I may need some assistance or verification
c) Not very confident, I may have difficulty determining the credibility and reliability
d) Not confident at all, I'm unsure how to evaluate information sources effectively

Have you sought input or perspectives from others who may have different viewpoints or expertise on the topic?
a) Yes, extensively
b) Yes, to some extent
c) No, but I have considered some differing perspectives
d) No, I haven't sought input or considered differing perspectives

Do you believe there are any significant gaps in your knowledge or information that could affect your decision-making?
a) No, I feel well-informed without any significant gaps in knowledge
b) Yes, there may be some gaps, but they are relatively minor
c) Yes, there are notable gaps in my knowledge or information that could impact my decision
d) I'm uncertain, I'm not sure if there are gaps in my knowledge or information

How important is it to you to have all the necessary information before making a decision on this topic?
a) Extremely important, I want to ensure I have all the facts before deciding
b) Moderately important, I prefer to have sufficient information but can make decisions with some uncertainty
c) Not very important, I can make decisions based on limited information or partial knowledge
d) Not important at all, I'm comfortable making decisions with minimal information or uncertainty

**Comment by JamesPHoughton** [comment]
What I really want with this survey is to have alternative dimensions that can help explain why a particular discussion topic might yield a different result for a particular group of people. If I can characterize the things people bring to the topic before the discussion starts,
