### ISSUE TITLE
Standard Demographic Survey

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#35]
We want to have a standard way of measuring participant demographics. This survey will likely be used across many different experiments, and should be as robust as possible. As with https://github.com/Watts-Lab/surveys/issues/34, we should look to other sources for validated sets of questions. 

@markwhiting @linneagandhi @TutiGomoka - what do we have for this already in the turkers panel?

**Comment by markwhiting** [comment]
@TutiGomoka And I are using a pretty [specific set of demographics](https://github.com/Watts-Lab/surveyor/blob/main/surveys/demographics.csv) that should have a lot of coverage and have a fair amount of motivation and validity. We should get those from everyone in the panel (eg all HT workers now have that data), so you might not need to separately.

In any case. I think we'd ask that you do at least these if you're going to also do others (to keep the panel consistent), but we can easily set up to invite anyone to do these as is.

**Comment by TutiGomoka** [comment]
Agreed with mark! And as a reminder also, you can find all the variables in our panel and their respective methods of collection in [this codebook](https://github.com/Watts-Lab/individual-mapping/blob/main/panel_codebook.csv)
