### ISSUE TITLE
✅ Survey Presentation Gut Check

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#60]
The following surveys are implemented in our surveys repo already:

- [Psychological Safety](https://www.chromatic.com/pullrequest?activeElementId=comparison-test-key-6328b871a0c4f0c1ebe088c2-1200&appId=6234a36a932a74003a2e9141&number=52&view=changes)
- [Voice](https://www.chromatic.com/pullrequest?activeElementId=comparison-test-key-632dd3f2a0c4f0c1eb11e4e7-1200&appId=6234a36a932a74003a2e9141&number=59&view=changes)
- [Quality Control](https://main--6234a36a932a74003a2e9141.chromatic.com/?path=/story/surveys-qualitycontrolsurvey--quality-control-survey)
- [Team Viability](https://main--6234a36a932a74003a2e9141.chromatic.com/?path=/story/surveys-teamviability--team-viability)

Our goal is that:
- each survey measures an independent construct
- surveys will be visually presented exactly as they are shown in the window (minus the surrounding github/storybook/chromatic test infrastructure)
- surveys will be used in sequence, such that submitting one takes you to the next
- surveys can be easily reused across projects in the lab, and by anyone who wants to replicate our research or do similar research (plug-and-play architecture)

## Gut check
These aren't the final surveys we're going to use in the deliberation experiment, so don't want to assess them yet for content, but I do want to check the presentation before we spend a lot of time implementing more surveys in the same format. Some questions that come to mind:

- Should participants see the survey title?
- Should we have the open response item in every survey?
- Is the formatting of the instructions and starting sentence ok? (e.g. "Please select the opinion that most closely reflects how much you agree with the following statements. "During this conversation, I felt...")
- Some surveys have 5-point scales, and some have 7. At the moment, these come from the source papers, but we could alternately set a standard for all the surveys in our lab. (What should it be?)
- How much should we adapt the survey language to focus on discussions/deliberation? Or should language be as generic as possible to use across projects?

**Comment by JamesPHoughton** [comment]
Should we use the exact wording? 
- depends on if its a survey that another researcher has already validated
- Some things (such as "if I made a mistake") are not particularly clear in the context of deliberation
- Others are not things you would actually do in the context of deliberation ("I can ask for help")
- There's a limit to how much surveys can be general anyways, ie, non-group experiments can't use surveys about groups. But it might make sense to write it so that any group experiment could use it.

**Comment by markwhiting** [comment]
> Should we have the title?

I generally don't, unless there is a specific reason, like to forecast that it is the last survey for them before they get paid.

> Should we have the open response item in every survey?

I think this is great at the end of an entire survey, but if you were using these in succession I am not sure you would always want it. That said, I do think it's a helpful opportunity. I don't know if theres good data on the impact of having an option like that.
